language: go
sudo: false
go:
    - 1.9

before_install:
    - go get github.com/go-playground/overalls
    - go install github.com/go-playground/overalls

script:
    - overalls -project=github.com/AndrewLader/go-tendo -covermode=count
    - mv overalls.coverprofile coverage.txt
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
